
###
POST https://api.aplansboster.dinas.social/api/v1/auth/login
Accept: application/json

{
    "identifier":"raihanoza18@gmail.com",
    "password": "mantap_Kali234"
}

###
GET https://api.aplansboster.dinas.social/api/v1/dashboard/dtks/count/administrative-area?limit=5&sort=DESC
###
GET https://api.aplansboster.dinas.social/api/v1/public/application/indigency-certificate/history
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hcGxhbnNib3N0ZXIuZGluYXMuc29jaWFsL2FwaS92MS9wdWJsaWMvYXV0aC9sb2dpbiIsImlhdCI6MTcwMjk1MjQ5MCwiZXhwIjoxNzAyOTU2MDkwLCJuYmYiOjE3MDI5NTI0OTAsImp0aSI6IkUydUtjM2IxQW5zNm1OQzkiLCJzdWIiOiI5YWRmZmI1Ny0yNjUwLTRmNTMtYTRhMC1kZjYwZTQ3MTNiMTAiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.b7P7vSeW8tt1r5xidAQuFe9Z8nWWRyi5-BmuCm_nj4Q

###
GET https://api.aplansboster.dinas.social/api/v1/service/dtks-application?status=1&assistance=PBI
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hcGxhbnNib3N0ZXIuZGluYXMuc29jaWFsL2FwaS92MS9hdXRoL2xvZ2luIiwiaWF0IjoxNzAyNTcxODA2LCJleHAiOjE3MDI1NzU0MDYsIm5iZiI6MTcwMjU3MTgwNiwianRpIjoiZ1FnMndGNVVhMFZQaFFCZCIsInN1YiI6IjlhZDg1MDUzLWUwN2EtNDA1MC1hYjNiLTBmYTJjZDNkY2E4ZCIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.E_9C2prkIhFJs-8DwIpLm_wBKA2iNg0nP3-RRJSSgM4



###
GET https://api.aplansboster.dinas.social/api/v1/service/indigency-certificate?application_status=pending&q=NURUL
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hcGxhbnNib3N0ZXIuZGluYXMuc29jaWFsL2FwaS92MS9hdXRoL2xvZ2luIiwiaWF0IjoxNzAyNTI4NjgwLCJleHAiOjE3MDI1MzIyODAsIm5iZiI6MTcwMjUyODY4MCwianRpIjoiQ0thbmJTNkdIeGFRWFBoRiIsInN1YiI6IjlhZDYyNDhkLWFjNWItNDc2Yi04NGUxLTc2Y2YzZjc5MDM4NiIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Rnagm3RKLhsSoL6us4i7e1FSQcLXGFviDGUlGIbSqM8


###
POST https://api.aplansboster.dinas.social/api/v1/indigency-certificate
###
DELETE https://api.aplansboster.dinas.social/api/v1/vulnerable-group-handling/9ac9e119-aaca-4931-b55e-964f96fbb7cc


### 
POST https://api.aplansboster.dinas.social/api/v1/indigency-certificate
Content-Type: application/json
Accept: application/json

{
    "applicant" : "9abcb4ad-9e3b-4862-a0e0-8f015745fc3e",
    "peopleConcerned" : "9abcb4ad-9e3b-4862-a0e0-8f015745fc3e",
    "certificateDestination" : "Sekolah",
    "issueDate" : "2022-03-03",
    "isDtks" : true
}