import Logo from './images/logo.png'
import LogoMini from './images/logo-minimize.png'
import BgLogin from './images/login-background.webp'
import BgDukcapil from './images/bg-dukcapil.svg'
import BgBansos from './images/bg-cekriwayat-bansos.webp'
import BgDataRehabsos from './images/bg-data-rehabsos.webp'
import BgDataDayasos from './images/bg-data-daysos.webp'
import BgDataLinjmasos from './images/bg-data-linjamsos.webp'
import BgLayananRehabsos from './images/bg-layanan-rehabsos.svg'
import BgLayananDayasos from './images/bg-layanan-dayasos.svg'
import BgLayananLinjmasos from './images/bg-layanan-linjamsos.svg'
import ImageCover from './images/image-cover.webp'
import BgCard from './images/bg-card.svg'
import DinsosLogo from './images/logo-dinsos.svg'
import MedanBerkahLogo from './images/medan-berkah.svg'
import NotFoundBansos from './icons/not-found-bansos.svg'
import Swafoto from './images/swafoto.webp'
import CekBansosIlustration from './icons/cek-bansos.svg'
import Substract from './images/Subtract.svg'
import NotFoundIllustration from './images/not-found.svg'
import NotFoundNumber from './images/not-found-number.svg'
import BgProfile from './images/bg-profile.svg'
import BgEmpty from './images/bg-empty.svg'
import Bgsuccessful from './images/bg-successful.svg'
import BgVerified from './images/bg-verified.svg'
import ForbidenNumber from './images/forbiden-number.svg'

export { Logo, BgLogin, LogoMini, BgDukcapil, BgBansos, BgDataRehabsos, BgDataDayasos, BgDataLinjmasos, BgLayananRehabsos, BgLayananDayasos, BgLayananLinjmasos, ImageCover, BgCard, DinsosLogo, MedanBerkahLogo, NotFoundBansos, Swafoto, CekBansosIlustration, Substract, NotFoundIllustration, NotFoundNumber, BgProfile, BgEmpty, Bgsuccessful, BgVerified, ForbidenNumber }
