#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling, testing and building your project before commiting'

# Check Prettier
npm run check-format ||
(
  echo 'Prettier Check Failed. Run npm run format, add changes and try commit again';
  false;
)


echo 'Success Commit';